{-# LANGUAGE OverloadedStrings, CPP #-}

module FormStructure.Usage where

#ifndef __HASTE__
import Data.Text.Lazy (Text)
#else
type Text = String
#endif

operations :: [Text]
operations =
  [ "Sequence motif discovery"
  , "Sequence motif recognition"
  , "Protein sequence feature detection"
  , "Epitope mapping"
  , "Protein post-translation modification site prediction"
  , "Protein signal peptide detection"
  , "Protein signal peptide detection (eukaryotes)"
  , "Protein signal peptide detection (bacteria)"
  , "Protein folding site prediction"
  , "Protein cleavage site prediction"
  , "Nucleic acid sequence feature detection"
  , "Conserved transcription regulatory sequence identification"
  , "Transposon prediction"
  , "PolyA signal detection"
  , "Quadruplex formation site detection"
  , "CpG island and isochore detection"
  , "Restriction site recognition"
  , "Restriction map drawing"
  , "Nucleosome formation or exclusion sequence prediction"
  , "Splice site prediction"
  , "SNP detection"
  , "SNP calling"
  , "Gene prediction"
  , "Integrated gene prediction"
  , "Operon prediction"
  , "Coding region prediction"
  , "Translation initiation site prediction"
  , "Selenocysteine insertion sequence (SECIS) prediction"
  , "Regulatory element prediction"
  , "Conserved transcription regulatory sequence identification"
  , "Promoter prediction"
  , "Transcription factor binding site prediction"
  , "Exonic splicing enhancer prediction"
  , "Transcription regulatory element prediction (DNA-cis)"
  , "Transcription regulatory element prediction (RNA-cis)"
  , "Transcription regulatory element prediction (trans)"
  , "microRNA detection"
  , "siRNA binding specificity prediction"
  , "siRNA duplex prediction"
  , "Matrix/scaffold attachment site prediction"
  , "tRNA gene prediction"
  , "Ab-initio gene prediction"
  , "Homology-based gene prediction"
  , "Genetic variation analysis"
  , "Genotyping"
  , "Polymorphism detection"
  , "Frameshift detection"
  , "Indel detection"
  , "SNP detection"
  , "SNP calling"
  , "Variant classification"
  , "Variant prioritisation"
  , "Variant calling"
  , "Structural variation discovery"
  , "Variant pattern analysis"
  , "Reference identification"
  , "Peak calling"
  , "Protein structure prediction"
  , "Ab initio structure prediction"
  , "Protein modelling"
  , "Protein modelling (mutation)"
  , "Protein modelling (backbone)"
  , "Protein modelling (side chains)"
  , "Protein modelling (loops)"
  , "Protein quaternary structure prediction"
  , "Nucleic acid structure prediction"
  , "RNA structure prediction"
  , "DNA structure prediction"
  , "Named-entity and concept recognition"
  , "Relation inference"
  , "Molecular dynamics simulation"
  , "Protein flexibility and motion analysis"
  , "Prediction and recognition (protein)"
  , "Protein property calculation"
  , "Protein property calculation (from structure)"
  , "Protein flexibility and motion analysis"
  , "Residue interaction calculation"
  , "Hydrogen bond calculation"
  , "Metal-bound cysteine detection"
  , "Protein-metal contact calculation"
  , "Salt bridge calculation"
  , "Residue distance calculation"
  , "Protein distance matrix calculation"
  , "Protein contact map calculation"
  , "Residue cluster calculation"
  , "Protein geometry calculation"
  , "Ramachandran plot calculation"
  , "Residue interaction prediction"
  , "3D-1D scoring matrix generation"
  , "Protein hydropathy calculation"
  , "Protein hydrophobic region calculation"
  , "Protein aliphatic index calculation"
  , "Protein hydrophobic moment plotting"
  , "Protein globularity prediction"
  , "Protein solubility prediction"
  , "Protein crystallizability prediction"
  , "Protein property calculation (from sequence)"
  , "Peptide immunogenicity prediction"
  , "Enzyme kinetics calculation"
  , "Protein sequence cleavage"
  , "Protein dipole moment calculation"
  , "Protein molecular weight calculation"
  , "Protein fragment weight comparison"
  , "Protein extinction coefficient calculation"
  , "Protein pH-dependent property calculation"
  , "Protein titration curve plotting"
  , "Protein isoelectric point calculation"
  , "Protein hydrogen exchange rate calculation"
  , "3D-1D scoring matrix generation"
  , "GPCR coupling selectivity prediction"
  , "Protein secondary structure prediction"
  , "Protein super-secondary structure prediction"
  , "Transmembrane protein prediction"
  , "GPCR prediction"
  , "Protein secondary structure prediction (integrated)"
  , "Protein secondary structure prediction (helices)"
  , "Protein secondary structure prediction (turns)"
  , "Protein secondary structure prediction (coils)"
  , "Protein secondary structure prediction (disulfide bonds)"
  , "Protein secondary structure assignment"
  , "Protein secondary structure assignment (from coordinate data)"
  , "Protein cysteine and disulfide bond assignment"
  , "Cysteine bridge detection"
  , "Free cysteine detection"
  , "Metal-bound cysteine detection"
  , "Protein secondary structure assignment (from CD data)"
  , "Protein folding pathway prediction"
  , "Protein modelling (mutation)"
  , "Protein structure prediction"
  , "Ab initio structure prediction"
  , "Protein modelling"
  , "Protein modelling (mutation)"
  , "Protein modelling (backbone)"
  , "Protein modelling (side chains)"
  , "Protein modelling (loops)"
  , "Protein quaternary structure prediction"
  , "Protein function prediction"
  , "Protein-protein interaction prediction"
  , "Protein subcellular localisation prediction"
  , "Protein signal peptide detection"
  , "Protein signal peptide detection (eukaryotes)"
  , "Protein signal peptide detection (bacteria)"
  , "Protein architecture recognition"
  , "Protein subcellular localisation prediction"
  , "Protein signal peptide detection"
  , "Protein signal peptide detection (eukaryotes)"
  , "Protein signal peptide detection (bacteria)"
  , "Protein interaction prediction"
  , "Peptide immunogenicity prediction"
  , "Molecular docking"
  , "Protein-ligand docking"
  , "GPCR coupling selectivity prediction"
  , "Protein-protein interaction prediction"
  , "Protein binding site prediction"
  , "Protein-nucleic acid binding prediction"
  , "Zinc finger prediction"
  , "Protein sequence alignment analysis"
  , "Residue interaction prediction"
  , "Protein feature detection"
  , "Protein structural motif recognition"
  , "Protein domain recognition"
  , "Protein peeling"
  , "Protein secondary structure prediction"
  , "Protein super-secondary structure prediction"
  , "Transmembrane protein prediction"
  , "GPCR prediction"
  , "Protein secondary structure prediction (integrated)"
  , "Protein secondary structure prediction (helices)"
  , "Protein secondary structure prediction (turns)"
  , "Protein secondary structure prediction (coils)"
  , "Protein secondary structure prediction (disulfide bonds)"
  , "Protein fold recognition"
  , "Sequence-to-3D-profile alignment"
  , "Protein threading"
  , "Protein binding site prediction"
  , "Protein-nucleic acid binding prediction"
  , "Zinc finger prediction"
  , "Protein sequence feature detection"
  , "Epitope mapping"
  , "Protein post-translation modification site prediction"
  , "Protein signal peptide detection"
  , "Protein signal peptide detection (eukaryotes)"
  , "Protein signal peptide detection (bacteria)"
  , "Protein folding site prediction"
  , "Protein cleavage site prediction"
  , "Prediction and recognition (nucleic acid)"
  , "Nucleic acid folding analysis"
  , "RNA secondary structure prediction"
  , "RNA secondary structure prediction (shape-based)"
  , "Nucleic acid folding energy calculation"
  , "Nucleic acid folding prediction (alignment-based)"
  , "Nucleic acid feature detection"
  , "Vector sequence detection"
  , "RNA secondary structure prediction"
  , "RNA secondary structure prediction (shape-based)"
  , "Repeat sequence detection"
  , "Nucleic acid sequence feature detection"
  , "Conserved transcription regulatory sequence identification"
  , "Transposon prediction"
  , "PolyA signal detection"
  , "Quadruplex formation site detection"
  , "CpG island and isochore detection"
  , "Restriction site recognition"
  , "Restriction map drawing"
  , "Nucleosome formation or exclusion sequence prediction"
  , "Splice site prediction"
  , "SNP detection"
  , "SNP calling"
  , "Gene prediction"
  , "Integrated gene prediction"
  , "Operon prediction"
  , "Coding region prediction"
  , "Translation initiation site prediction"
  , "Selenocysteine insertion sequence (SECIS) prediction"
  , "Regulatory element prediction"
  , "Conserved transcription regulatory sequence identification"
  , "Promoter prediction"
  , "Transcription factor binding site prediction"
  , "Exonic splicing enhancer prediction"
  , "Transcription regulatory element prediction (DNA-cis)"
  , "Transcription regulatory element prediction (RNA-cis)"
  , "Transcription regulatory element prediction (trans)"
  , "microRNA detection"
  , "siRNA binding specificity prediction"
  , "siRNA duplex prediction"
  , "Matrix/scaffold attachment site prediction"
  , "tRNA gene prediction"
  , "Ab-initio gene prediction"
  , "Homology-based gene prediction"
  , "Genetic variation analysis"
  , "Genotyping"
  , "Polymorphism detection"
  , "Frameshift detection"
  , "Indel detection"
  , "SNP detection"
  , "SNP calling"
  , "Variant classification"
  , "Variant prioritisation"
  , "Variant calling"
  , "Structural variation discovery"
  , "Variant pattern analysis"
  , "Reference identification"
  , "Peak calling"
  , "Nucleic acid structure prediction"
  , "RNA structure prediction"
  , "DNA structure prediction"
  , "Genetic code prediction"
  , "Primer and probe design"
  , "PCR primer design"
  , "Microarray probe design"
  , "Gene regulatory network prediction"
  , "Splicing model analysis"
  , "Splice transcript prediction"
  , "Nucleic acid sequence alignment analysis"
  , "Chimeric sequence detection"
  , "Recombination detection"
  , "Indel detection"
  , "SNP detection"
  , "SNP calling"
  , "DNA substitution modelling"
  , "Pathway or network prediction"
  , "Gene regulatory network prediction"
  , "Protein interaction network prediction"
  , "Virulence prediction"
  , "Antimicrobial resistance prediction"
  , "Sequence feature comparison"
  , "Genome feature comparison"
  , "Sequence alignment comparison"
  , "Phylogenetic tree comparison"
  , "Phylogenetic tree generation (consensus)"
  , "Phylogenetic sub/super tree detection"
  , "Phylogenetic tree distances calculation"
  , "Sequence comparison"
  , "Sequence motif comparison"
  , "Sequence word comparison"
  , "Dotplot plotting"
  , "Sequence distance matrix generation"
  , "Sequence redundancy removal"
  , "Sequence clustering"
  , "Functional clustering"
  , "Sequence alignment"
  , "Structure-based sequence alignment"
  , "Profile-profile alignment"
  , "Sequence-to-profile alignment"
  , "Pairwise sequence alignment"
  , "Multiple sequence alignment"
  , "Local alignment"
  , "Global alignment"
  , "Constrained sequence alignment"
  , "Tree-based sequence alignment"
  , "Genome alignment"
  , "Read mapping"
  , "Split read mapping"
  , "Sequence similarity search"
  , "Representative sequence identification"
  , "Nucleic acid sequence comparison"
  , "Vector sequence detection"
  , "Splicing model analysis"
  , "Splice transcript prediction"
  , "Sequencing error detection"
  , "Frameshift detection"
  , "Genetic variation analysis"
  , "Genotyping"
  , "Polymorphism detection"
  , "Frameshift detection"
  , "Indel detection"
  , "SNP detection"
  , "SNP calling"
  , "Variant classification"
  , "Variant prioritisation"
  , "Variant calling"
  , "Structural variation discovery"
  , "Variant pattern analysis"
  , "Reference identification"
  , "Genome comparison"
  , "Protein sequence comparison"
  , "Structure comparison"
  , "Structure alignment"
  , "3D profile-to-3D profile alignment"
  , "Pairwise structure alignment"
  , "Multiple structure alignment"
  , "Local structure alignment"
  , "Global structure alignment"
  , "Structural similarity search"
  , "Protein structure comparison"
  , "Nucleic acid structure comparison"
  , "Chemical redundancy removal"
  , "Molecular surface comparison"
  , "Secondary structure comparison"
  , "Protein secondary structure comparison"
  , "Protein secondary structure alignment generation"
  , "Protein architecture comparison"
  , "Protein comparison"
  , "Protein fold recognition"
  , "Sequence-to-3D-profile alignment"
  , "Protein threading"
  , "Protein function comparison"
  , "Protein interaction network comparison"
  , "Protein structure comparison"
  , "Protein secondary structure comparison"
  , "Protein secondary structure alignment generation"
  , "Protein architecture comparison"
  , "Protein sequence comparison"
  , "Protein property comparison"
  , "Protein fragment weight comparison"
  , "Differential protein expression analysis"
  , "Nucleic acid comparison"
  , "Codon usage table comparison"
  , "Gene expression profile comparison"
  , "Gene expression profile clustering"
  , "Gene expression correlation analysis"
  , "Nucleic acid sequence comparison"
  , "Vector sequence detection"
  , "Splicing model analysis"
  , "Splice transcript prediction"
  , "Sequencing error detection"
  , "Frameshift detection"
  , "Genetic variation analysis"
  , "Genotyping"
  , "Polymorphism detection"
  , "Frameshift detection"
  , "Indel detection"
  , "SNP detection"
  , "SNP calling"
  , "Variant classification"
  , "Variant prioritisation"
  , "Variant calling"
  , "Structural variation discovery"
  , "Variant pattern analysis"
  , "Reference identification"
  , "Genome comparison"
  , "Nucleic acid structure comparison"
  , "Differential gene expression analysis"
  , "ID mapping"
  , "Ontology comparison"
  , "Article comparison"
  , "Document similarity calculation"
  , "Document clustering"
  , "Database comparison"
  , "Sample comparison"
  , "Differential gene expression analysis"
  , "Differential gene expression analysis"
  , "Differential protein expression analysis"
  , "Molecular model refinement"
  , "Molecular replacement"
  , "Rigid body refinement"
  , "Sequence alignment refinement"
  , "Nucleic acid folding analysis"
  , "RNA secondary structure prediction"
  , "RNA secondary structure prediction (shape-based)"
  , "Nucleic acid folding energy calculation"
  , "Nucleic acid folding prediction (alignment-based)"
  , "Protein modelling"
  , "Protein modelling (mutation)"
  , "Protein modelling (backbone)"
  , "Protein modelling (side chains)"
  , "Protein modelling (loops)"
  , "DNA substitution modelling"
  , "Protein folding analysis"
  , "Protein folding simulation"
  , "Protein folding pathway prediction"
  , "Protein folding site prediction"
  , "Molecular dynamics simulation"
  , "Protein flexibility and motion analysis"
  , "Splicing model analysis"
  , "Splice transcript prediction"
  , "Network simulation"
  , "Metabolic network modelling"
  , "Simulated gene expression data generation"
  , "Protein model validation"
  , "Residue bump detection"
  , "Residue packing validation"
  , "Protein geometry validation"
  , "Ramachandran plot validation"
  , "Maximum occurence analysis"
  , "Format validation"
  , "Sequence alignment validation"
  , "Phylogenetic tree bootstrapping"
  , "Sequence assembly validation"
  , "Sequencing quality control"
  , "Read pre-processing"
  , "Variant filtering"
  , "Validation of peptide-spectrum matches"
  , "Target-Decoy"
  , "Epitope mapping"
  , "Gene expression profile pathway mapping"
  , "DNA mapping"
  , "Genetic mapping"
  , "Haplotype mapping"
  , "Sequence tag mapping"
  , "Physical mapping"
  , "Radiation Hybrid Mapping"
  , "Sequence tagged site (STS) mapping"
  , "Bisulfite mapping"
  , "Read mapping"
  , "Split read mapping"
  , "Methylation calling"
  , "Methylation level analysis (global)"
  , "Methylation level analysis (gene-specific)"
  , "ID mapping"
  , "Database comparison"
  , "Microarray probe design"
  , "Nucleic acid design"
  , "Structured RNA prediction and optimisation"
  , "DNA vaccine design"
  , "Primer and probe design"
  , "PCR primer design"
  , "Microarray probe design"
  , "Sequence alignment"
  , "Structure-based sequence alignment"
  , "Profile-profile alignment"
  , "Sequence-to-profile alignment"
  , "Pairwise sequence alignment"
  , "Multiple sequence alignment"
  , "Local alignment"
  , "Global alignment"
  , "Constrained sequence alignment"
  , "Tree-based sequence alignment"
  , "Genome alignment"
  , "Read mapping"
  , "Split read mapping"
  , "Structure alignment"
  , "3D profile-to-3D profile alignment"
  , "Pairwise structure alignment"
  , "Multiple structure alignment"
  , "Local structure alignment"
  , "Global structure alignment"
  , "Sequence-to-3D-profile alignment"
  , "Protein threading"
  , "Text mining"
  , "Named-entity and concept recognition"
  , "Relation inference"
  , "Phylogenetic tree analysis"
  , "Phylogenetic tree generation"
  , "Phylogenetic tree generation (data centric)"
  , "Phylogenetic tree generation (from molecular sequences)"
  , "Phylogenetic footprinting / shadowing"
  , "Phylogenetic species tree construction"
  , "Phylogenetic tree generation (from continuous quantitative characters)"
  , "Phylogenetic tree generation (from gene frequencies)"
  , "Phylogenetic tree construction (from polymorphism data)"
  , "Phylogenetic tree generation (method centric)"
  , "Phylogenetic tree generation (parsimony methods)"
  , "Phylogenetic tree generation (minimum distance methods)"
  , "Phylogenetic tree generation (maximum likelihood and Bayesian methods)"
  , "Phylogenetic tree generation (quartet methods)"
  , "Phylogenetic tree generation (AI methods)"
  , "Phylogenetic tree generation (consensus)"
  , "Phylogenetic tree reconstruction"
  , "Phylogenetic tree comparison"
  , "Phylogenetic tree generation (consensus)"
  , "Phylogenetic sub/super tree detection"
  , "Phylogenetic tree distances calculation"
  , "Phylogenetic tree editing"
  , "Phylogenetic tree analysis (shape)"
  , "Phylogenetic tree bootstrapping"
  , "Phylogenetic tree analysis (gene family prediction)"
  , "Phylogenetic tree analysis (natural selection)"
  , "Phylogenetic tree visualisation"
  , "Ancestral reconstruction"
  , "Sequence analysis"
  , "Sequence generation"
  , "Random sequence generation"
  , "Sequence generation (nucleic acid)"
  , "Nucleic acid sequence reverse and complement"
  , "Nucleic acid restriction digest"
  , "Base-calling"
  , "Sequence generation (protein)"
  , "Protein sequence cleavage"
  , "de Novo sequencing"
  , "Probabilistic sequence generation"
  , "Sequence editing"
  , "Sequence merging"
  , "Sequence conversion"
  , "DNA translation"
  , "DNA transcription"
  , "DNA back-translation"
  , "Sequence mutation and randomisation"
  , "Sequence masking"
  , "Sequence cutting"
  , "Sequence trimming"
  , "Primer removal"
  , "Restriction site creation"
  , "Sequence file editing"
  , "Sequence composition calculation"
  , "Sequence complexity calculation"
  , "Sequence ambiguity calculation"
  , "Repeat sequence organisation analysis"
  , "Nucleic acid density plotting"
  , "k-mer counting"
  , "Repeat sequence analysis"
  , "Repeat sequence detection"
  , "Repeat sequence organisation analysis"
  , "Sequence feature detection"
  , "Sequence motif discovery"
  , "Sequence motif recognition"
  , "Protein sequence feature detection"
  , "Epitope mapping"
  , "Protein post-translation modification site prediction"
  , "Protein signal peptide detection"
  , "Protein signal peptide detection (eukaryotes)"
  , "Protein signal peptide detection (bacteria)"
  , "Protein folding site prediction"
  , "Protein cleavage site prediction"
  , "Nucleic acid sequence feature detection"
  , "Conserved transcription regulatory sequence identification"
  , "Transposon prediction"
  , "PolyA signal detection"
  , "Quadruplex formation site detection"
  , "CpG island and isochore detection"
  , "Restriction site recognition"
  , "Restriction map drawing"
  , "Nucleosome formation or exclusion sequence prediction"
  , "Splice site prediction"
  , "SNP detection"
  , "SNP calling"
  , "Gene prediction"
  , "Integrated gene prediction"
  , "Operon prediction"
  , "Coding region prediction"
  , "Translation initiation site prediction"
  , "Selenocysteine insertion sequence (SECIS) prediction"
  , "Regulatory element prediction"
  , "Conserved transcription regulatory sequence identification"
  , "Promoter prediction"
  , "Transcription factor binding site prediction"
  , "Exonic splicing enhancer prediction"
  , "Transcription regulatory element prediction (DNA-cis)"
  , "Transcription regulatory element prediction (RNA-cis)"
  , "Transcription regulatory element prediction (trans)"
  , "microRNA detection"
  , "siRNA binding specificity prediction"
  , "siRNA duplex prediction"
  , "Matrix/scaffold attachment site prediction"
  , "tRNA gene prediction"
  , "Ab-initio gene prediction"
  , "Homology-based gene prediction"
  , "Genetic variation analysis"
  , "Genotyping"
  , "Polymorphism detection"
  , "Frameshift detection"
  , "Indel detection"
  , "SNP detection"
  , "SNP calling"
  , "Variant classification"
  , "Variant prioritisation"
  , "Variant calling"
  , "Structural variation discovery"
  , "Variant pattern analysis"
  , "Reference identification"
  , "Peak calling"
  , "Sequence feature comparison"
  , "Genome feature comparison"
  , "Sequence alignment analysis"
  , "Sequence alignment comparison"
  , "Sequence profile generation"
  , "Sequence alignment validation"
  , "Sequence alignment analysis (conservation)"
  , "Sequence alignment analysis (site correlation)"
  , "Sequence alignment refinement"
  , "Protein sequence alignment analysis"
  , "Residue interaction prediction"
  , "Nucleic acid sequence alignment analysis"
  , "Chimeric sequence detection"
  , "Recombination detection"
  , "Indel detection"
  , "SNP detection"
  , "SNP calling"
  , "DNA substitution modelling"
  , "Sequence alignment"
  , "Structure-based sequence alignment"
  , "Profile-profile alignment"
  , "Sequence-to-profile alignment"
  , "Pairwise sequence alignment"
  , "Multiple sequence alignment"
  , "Local alignment"
  , "Global alignment"
  , "Constrained sequence alignment"
  , "Tree-based sequence alignment"
  , "Genome alignment"
  , "Read mapping"
  , "Split read mapping"
  , "Sequence database search"
  , "Sequence similarity search"
  , "Sequence database search (by property)"
  , "Phylogenetic tree generation (from molecular sequences)"
  , "Phylogenetic footprinting / shadowing"
  , "Phylogenetic species tree construction"
  , "Sequence visualisation"
  , "Dotplot plotting"
  , "Sequence assembly visualisation"
  , "Genome visualisation"
  , "Sequence file editing"
  , "Sequence motif analysis"
  , "Sequence motif discovery"
  , "Sequence motif recognition"
  , "Sequence motif comparison"
  , "Sequence comparison"
  , "Sequence motif comparison"
  , "Sequence word comparison"
  , "Dotplot plotting"
  , "Sequence distance matrix generation"
  , "Sequence redundancy removal"
  , "Sequence clustering"
  , "Functional clustering"
  , "Sequence alignment"
  , "Structure-based sequence alignment"
  , "Profile-profile alignment"
  , "Sequence-to-profile alignment"
  , "Pairwise sequence alignment"
  , "Multiple sequence alignment"
  , "Local alignment"
  , "Global alignment"
  , "Constrained sequence alignment"
  , "Tree-based sequence alignment"
  , "Genome alignment"
  , "Read mapping"
  , "Split read mapping"
  , "Sequence similarity search"
  , "Representative sequence identification"
  , "Nucleic acid sequence comparison"
  , "Vector sequence detection"
  , "Splicing model analysis"
  , "Splice transcript prediction"
  , "Sequencing error detection"
  , "Frameshift detection"
  , "Genetic variation analysis"
  , "Genotyping"
  , "Polymorphism detection"
  , "Frameshift detection"
  , "Indel detection"
  , "SNP detection"
  , "SNP calling"
  , "Variant classification"
  , "Variant prioritisation"
  , "Variant calling"
  , "Structural variation discovery"
  , "Variant pattern analysis"
  , "Reference identification"
  , "Genome comparison"
  , "Protein sequence comparison"
  , "Nucleic acid sequence analysis"
  , "Nucleic acid property calculation"
  , "Nucleic acid restriction digest"
  , "Nucleic acid thermodynamic property calculation"
  , "Nucleic acid melting profile plotting"
  , "Nucleic acid stitch profile plotting"
  , "Nucleic acid melting curve plotting"
  , "Nucleic acid probability profile plotting"
  , "Nucleic acid temperature profile plotting"
  , "Nucleic acid curvature calculation"
  , "Linkage analysis"
  , "Haplotype mapping"
  , "Linkage disequilibrium calculation"
  , "Codon usage analysis"
  , "Base position variability plotting"
  , "Genetic code prediction"
  , "Codon usage table processing"
  , "Codon usage table generation"
  , "Codon usage table comparison"
  , "Codon usage bias calculation"
  , "Codon usage bias plotting"
  , "Codon usage fraction calculation"
  , "Virtual PCR"
  , "Sequence assembly"
  , "Mapping assembly"
  , "De-novo assembly"
  , "Genome assembly"
  , "EST assembly"
  , "Localised reassembly"
  , "Scaffolding"
  , "Scaffold gap completion"
  , "Exome assembly"
  , "Transcriptome assembly"
  , "Cross-assembly"
  , "Nucleic acid feature detection"
  , "Vector sequence detection"
  , "RNA secondary structure prediction"
  , "RNA secondary structure prediction (shape-based)"
  , "Repeat sequence detection"
  , "Nucleic acid sequence feature detection"
  , "Conserved transcription regulatory sequence identification"
  , "Transposon prediction"
  , "PolyA signal detection"
  , "Quadruplex formation site detection"
  , "CpG island and isochore detection"
  , "Restriction site recognition"
  , "Restriction map drawing"
  , "Nucleosome formation or exclusion sequence prediction"
  , "Splice site prediction"
  , "SNP detection"
  , "SNP calling"
  , "Gene prediction"
  , "Integrated gene prediction"
  , "Operon prediction"
  , "Coding region prediction"
  , "Translation initiation site prediction"
  , "Selenocysteine insertion sequence (SECIS) prediction"
  , "Regulatory element prediction"
  , "Conserved transcription regulatory sequence identification"
  , "Promoter prediction"
  , "Transcription factor binding site prediction"
  , "Exonic splicing enhancer prediction"
  , "Transcription regulatory element prediction (DNA-cis)"
  , "Transcription regulatory element prediction (RNA-cis)"
  , "Transcription regulatory element prediction (trans)"
  , "microRNA detection"
  , "siRNA binding specificity prediction"
  , "siRNA duplex prediction"
  , "Matrix/scaffold attachment site prediction"
  , "tRNA gene prediction"
  , "Ab-initio gene prediction"
  , "Homology-based gene prediction"
  , "Genetic variation analysis"
  , "Genotyping"
  , "Polymorphism detection"
  , "Frameshift detection"
  , "Indel detection"
  , "SNP detection"
  , "SNP calling"
  , "Variant classification"
  , "Variant prioritisation"
  , "Variant calling"
  , "Structural variation discovery"
  , "Variant pattern analysis"
  , "Reference identification"
  , "Peak calling"
  , "Nucleic acid structure prediction"
  , "RNA structure prediction"
  , "DNA structure prediction"
  , "Nucleic acid sequence comparison"
  , "Vector sequence detection"
  , "Splicing model analysis"
  , "Splice transcript prediction"
  , "Sequencing error detection"
  , "Frameshift detection"
  , "Genetic variation analysis"
  , "Genotyping"
  , "Polymorphism detection"
  , "Frameshift detection"
  , "Indel detection"
  , "SNP detection"
  , "SNP calling"
  , "Variant classification"
  , "Variant prioritisation"
  , "Variant calling"
  , "Structural variation discovery"
  , "Variant pattern analysis"
  , "Reference identification"
  , "Genome comparison"
  , "Nucleic acid design"
  , "Structured RNA prediction and optimisation"
  , "DNA vaccine design"
  , "Primer and probe design"
  , "PCR primer design"
  , "Microarray probe design"
  , "Sequence assembly validation"
  , "Sequence contamination filtering"
  , "Community profiling"
  , "Methylation analysis"
  , "Methylation calling"
  , "Methylation level analysis (global)"
  , "Methylation level analysis (gene-specific)"
  , "Sequencing quality control"
  , "Read pre-processing"
  , "Variant filtering"
  , "Read pre-processing"
  , "Species frequency estimation"
  , "Read depth analysis"
  , "Copy number estimation"
  , "Variant filtering"
  , "Differential binding analysis"
  , "RNA-Seq analysis"
  , "RNA-seq read count analysis"
  , "RNA-seq time series data analysis"
  , "Protein sequence analysis"
  , "Protein secondary structure prediction"
  , "Protein super-secondary structure prediction"
  , "Transmembrane protein prediction"
  , "GPCR prediction"
  , "Protein secondary structure prediction (integrated)"
  , "Protein secondary structure prediction (helices)"
  , "Protein secondary structure prediction (turns)"
  , "Protein secondary structure prediction (coils)"
  , "Protein secondary structure prediction (disulfide bonds)"
  , "Protein fold recognition"
  , "Sequence-to-3D-profile alignment"
  , "Protein threading"
  , "Protein structure prediction"
  , "Ab initio structure prediction"
  , "Protein modelling"
  , "Protein modelling (mutation)"
  , "Protein modelling (backbone)"
  , "Protein modelling (side chains)"
  , "Protein modelling (loops)"
  , "Protein quaternary structure prediction"
  , "Protein sequence comparison"
  , "Protein sequence feature detection"
  , "Epitope mapping"
  , "Protein post-translation modification site prediction"
  , "Protein signal peptide detection"
  , "Protein signal peptide detection (eukaryotes)"
  , "Protein signal peptide detection (bacteria)"
  , "Protein folding site prediction"
  , "Protein cleavage site prediction"
  , "Protein property calculation (from sequence)"
  , "Peptide immunogenicity prediction"
  , "Enzyme kinetics calculation"
  , "Protein sequence cleavage"
  , "Protein dipole moment calculation"
  , "Protein molecular weight calculation"
  , "Protein fragment weight comparison"
  , "Protein extinction coefficient calculation"
  , "Protein pH-dependent property calculation"
  , "Protein titration curve plotting"
  , "Protein isoelectric point calculation"
  , "Protein hydrogen exchange rate calculation"
  , "3D-1D scoring matrix generation"
  , "GPCR coupling selectivity prediction"
  , "Sequence classification"
  , "Variant classification"
  , "Taxonomic classification"
  , "Virulence prediction"
  , "Antimicrobial resistance prediction"
  , "Structure analysis"
  , "Structure prediction"
  , "Protein structure prediction"
  , "Ab initio structure prediction"
  , "Protein modelling"
  , "Protein modelling (mutation)"
  , "Protein modelling (backbone)"
  , "Protein modelling (side chains)"
  , "Protein modelling (loops)"
  , "Protein quaternary structure prediction"
  , "Nucleic acid structure prediction"
  , "RNA structure prediction"
  , "DNA structure prediction"
  , "Structure alignment"
  , "3D profile-to-3D profile alignment"
  , "Pairwise structure alignment"
  , "Multiple structure alignment"
  , "Local structure alignment"
  , "Global structure alignment"
  , "3D profile generation"
  , "Molecular model refinement"
  , "Molecular replacement"
  , "Rigid body refinement"
  , "Molecular docking"
  , "Protein-ligand docking"
  , "Structure visualisation"
  , "Surface rendering"
  , "Transmembrane protein visualisation"
  , "Helical wheel drawing"
  , "Topology diagram drawing"
  , "Protein structure analysis"
  , "Protein property calculation (from structure)"
  , "Protein flexibility and motion analysis"
  , "Residue interaction calculation"
  , "Hydrogen bond calculation"
  , "Metal-bound cysteine detection"
  , "Protein-metal contact calculation"
  , "Salt bridge calculation"
  , "Residue distance calculation"
  , "Protein distance matrix calculation"
  , "Protein contact map calculation"
  , "Residue cluster calculation"
  , "Protein geometry calculation"
  , "Ramachandran plot calculation"
  , "Residue interaction prediction"
  , "3D-1D scoring matrix generation"
  , "Protein structural motif recognition"
  , "Protein domain recognition"
  , "Protein peeling"
  , "Protein architecture analysis"
  , "Protein architecture comparison"
  , "Protein architecture recognition"
  , "Protein fold recognition"
  , "Sequence-to-3D-profile alignment"
  , "Protein threading"
  , "Protein structure assignment"
  , "Protein model validation"
  , "Residue bump detection"
  , "Residue packing validation"
  , "Protein geometry validation"
  , "Ramachandran plot validation"
  , "Maximum occurence analysis"
  , "Protein modelling"
  , "Protein modelling (mutation)"
  , "Protein modelling (backbone)"
  , "Protein modelling (side chains)"
  , "Protein modelling (loops)"
  , "Protein secondary structure assignment (from coordinate data)"
  , "Protein cysteine and disulfide bond assignment"
  , "Cysteine bridge detection"
  , "Free cysteine detection"
  , "Metal-bound cysteine detection"
  , "Molecular dynamics simulation"
  , "Protein flexibility and motion analysis"
  , "Nucleic acid structure analysis"
  , "Nucleic acid folding analysis"
  , "RNA secondary structure prediction"
  , "RNA secondary structure prediction (shape-based)"
  , "Nucleic acid folding energy calculation"
  , "Nucleic acid folding prediction (alignment-based)"
  , "RNA secondary structure analysis"
  , "RNA secondary structure prediction"
  , "RNA secondary structure prediction (shape-based)"
  , "RNA secondary structure alignment"
  , "RNA structure covariance model generation"
  , "Nucleic acid structure comparison"
  , "Structure comparison"
  , "Structure alignment"
  , "3D profile-to-3D profile alignment"
  , "Pairwise structure alignment"
  , "Multiple structure alignment"
  , "Local structure alignment"
  , "Global structure alignment"
  , "Structural similarity search"
  , "Protein structure comparison"
  , "Nucleic acid structure comparison"
  , "Chemical redundancy removal"
  , "Molecular surface comparison"
  , "Structure classification"
  , "Protein architecture recognition"
  , "Molecular surface analysis"
  , "Accessible surface calculation"
  , "Molecular surface calculation"
  , "Surface rendering"
  , "Molecular surface comparison"
  , "Diffraction data analysis"
  , "Diffraction data reduction"
  , "Diffraction data integration"
  , "Phasing"
  , "Single particle analysis"
  , "Single particle alignment and classification"
  , "Gene expression analysis"
  , "Gene expression profiling"
  , "Gene expression profile comparison"
  , "Gene expression profile clustering"
  , "Gene expression correlation analysis"
  , "Gene expression profile pathway mapping"
  , "Microarray data rendering"
  , "Heat map generation"
  , "Microarray cluster textual view generation"
  , "Microarray wave graph plotting"
  , "Microarray dendrograph plotting"
  , "Microarray proximity map plotting"
  , "Microarray tree or dendrogram rendering"
  , "Microarray principal component plotting"
  , "Microarray scatter plot plotting"
  , "Whole microarray graph plotting"
  , "Microarray tree-map rendering"
  , "Microarray Box-Whisker plot plotting"
  , "Gene-set enrichment analysis"
  , "Gene set testing"
  , "Gene-set enrichment analysis"
  , "Gene expression QTL analysis"
  , "Pathway or network analysis"
  , "Protein interaction network analysis"
  , "Protein interaction network comparison"
  , "Gene expression profile pathway mapping"
  , "Gene regulatory network analysis"
  , "Pathway or network visualisation"
  , "Protein interaction network rendering"
  , "Pathway or network prediction"
  , "Gene regulatory network prediction"
  , "Protein interaction network prediction"
  , "Weighted correlation network analysis"
  , "Nucleic acid analysis"
  , "Nucleic acid sequence analysis"
  , "Nucleic acid property calculation"
  , "Nucleic acid restriction digest"
  , "Nucleic acid thermodynamic property calculation"
  , "Nucleic acid melting profile plotting"
  , "Nucleic acid stitch profile plotting"
  , "Nucleic acid melting curve plotting"
  , "Nucleic acid probability profile plotting"
  , "Nucleic acid temperature profile plotting"
  , "Nucleic acid curvature calculation"
  , "Linkage analysis"
  , "Haplotype mapping"
  , "Linkage disequilibrium calculation"
  , "Codon usage analysis"
  , "Base position variability plotting"
  , "Genetic code prediction"
  , "Codon usage table processing"
  , "Codon usage table generation"
  , "Codon usage table comparison"
  , "Codon usage bias calculation"
  , "Codon usage bias plotting"
  , "Codon usage fraction calculation"
  , "Virtual PCR"
  , "Sequence assembly"
  , "Mapping assembly"
  , "De-novo assembly"
  , "Genome assembly"
  , "EST assembly"
  , "Localised reassembly"
  , "Scaffolding"
  , "Scaffold gap completion"
  , "Exome assembly"
  , "Transcriptome assembly"
  , "Cross-assembly"
  , "Nucleic acid feature detection"
  , "Vector sequence detection"
  , "RNA secondary structure prediction"
  , "RNA secondary structure prediction (shape-based)"
  , "Repeat sequence detection"
  , "Nucleic acid sequence feature detection"
  , "Conserved transcription regulatory sequence identification"
  , "Transposon prediction"
  , "PolyA signal detection"
  , "Quadruplex formation site detection"
  , "CpG island and isochore detection"
  , "Restriction site recognition"
  , "Restriction map drawing"
  , "Nucleosome formation or exclusion sequence prediction"
  , "Splice site prediction"
  , "SNP detection"
  , "SNP calling"
  , "Gene prediction"
  , "Integrated gene prediction"
  , "Operon prediction"
  , "Coding region prediction"
  , "Translation initiation site prediction"
  , "Selenocysteine insertion sequence (SECIS) prediction"
  , "Regulatory element prediction"
  , "Conserved transcription regulatory sequence identification"
  , "Promoter prediction"
  , "Transcription factor binding site prediction"
  , "Exonic splicing enhancer prediction"
  , "Transcription regulatory element prediction (DNA-cis)"
  , "Transcription regulatory element prediction (RNA-cis)"
  , "Transcription regulatory element prediction (trans)"
  , "microRNA detection"
  , "siRNA binding specificity prediction"
  , "siRNA duplex prediction"
  , "Matrix/scaffold attachment site prediction"
  , "tRNA gene prediction"
  , "Ab-initio gene prediction"
  , "Homology-based gene prediction"
  , "Genetic variation analysis"
  , "Genotyping"
  , "Polymorphism detection"
  , "Frameshift detection"
  , "Indel detection"
  , "SNP detection"
  , "SNP calling"
  , "Variant classification"
  , "Variant prioritisation"
  , "Variant calling"
  , "Structural variation discovery"
  , "Variant pattern analysis"
  , "Reference identification"
  , "Peak calling"
  , "Nucleic acid structure prediction"
  , "RNA structure prediction"
  , "DNA structure prediction"
  , "Nucleic acid sequence comparison"
  , "Vector sequence detection"
  , "Splicing model analysis"
  , "Splice transcript prediction"
  , "Sequencing error detection"
  , "Frameshift detection"
  , "Genetic variation analysis"
  , "Genotyping"
  , "Polymorphism detection"
  , "Frameshift detection"
  , "Indel detection"
  , "SNP detection"
  , "SNP calling"
  , "Variant classification"
  , "Variant prioritisation"
  , "Variant calling"
  , "Structural variation discovery"
  , "Variant pattern analysis"
  , "Reference identification"
  , "Genome comparison"
  , "Nucleic acid design"
  , "Structured RNA prediction and optimisation"
  , "DNA vaccine design"
  , "Primer and probe design"
  , "PCR primer design"
  , "Microarray probe design"
  , "Sequence assembly validation"
  , "Sequence contamination filtering"
  , "Community profiling"
  , "Methylation analysis"
  , "Methylation calling"
  , "Methylation level analysis (global)"
  , "Methylation level analysis (gene-specific)"
  , "Sequencing quality control"
  , "Read pre-processing"
  , "Variant filtering"
  , "Read pre-processing"
  , "Species frequency estimation"
  , "Read depth analysis"
  , "Copy number estimation"
  , "Variant filtering"
  , "Differential binding analysis"
  , "RNA-Seq analysis"
  , "RNA-seq read count analysis"
  , "RNA-seq time series data analysis"
  , "Nucleic acid structure analysis"
  , "Nucleic acid folding analysis"
  , "RNA secondary structure prediction"
  , "RNA secondary structure prediction (shape-based)"
  , "Nucleic acid folding energy calculation"
  , "Nucleic acid folding prediction (alignment-based)"
  , "RNA secondary structure analysis"
  , "RNA secondary structure prediction"
  , "RNA secondary structure prediction (shape-based)"
  , "RNA secondary structure alignment"
  , "RNA structure covariance model generation"
  , "Nucleic acid structure comparison"
  , "Nucleic acid sequence alignment analysis"
  , "Chimeric sequence detection"
  , "Recombination detection"
  , "Indel detection"
  , "SNP detection"
  , "SNP calling"
  , "DNA substitution modelling"
  , "Protein analysis"
  , "Protein property calculation"
  , "Protein property calculation (from structure)"
  , "Protein flexibility and motion analysis"
  , "Residue interaction calculation"
  , "Hydrogen bond calculation"
  , "Metal-bound cysteine detection"
  , "Protein-metal contact calculation"
  , "Salt bridge calculation"
  , "Residue distance calculation"
  , "Protein distance matrix calculation"
  , "Protein contact map calculation"
  , "Residue cluster calculation"
  , "Protein geometry calculation"
  , "Ramachandran plot calculation"
  , "Residue interaction prediction"
  , "3D-1D scoring matrix generation"
  , "Protein hydropathy calculation"
  , "Protein hydrophobic region calculation"
  , "Protein aliphatic index calculation"
  , "Protein hydrophobic moment plotting"
  , "Protein globularity prediction"
  , "Protein solubility prediction"
  , "Protein crystallizability prediction"
  , "Protein property calculation (from sequence)"
  , "Peptide immunogenicity prediction"
  , "Enzyme kinetics calculation"
  , "Protein sequence cleavage"
  , "Protein dipole moment calculation"
  , "Protein molecular weight calculation"
  , "Protein fragment weight comparison"
  , "Protein extinction coefficient calculation"
  , "Protein pH-dependent property calculation"
  , "Protein titration curve plotting"
  , "Protein isoelectric point calculation"
  , "Protein hydrogen exchange rate calculation"
  , "3D-1D scoring matrix generation"
  , "GPCR coupling selectivity prediction"
  , "Transmembrane protein analysis"
  , "Transmembrane protein prediction"
  , "GPCR prediction"
  , "GPCR analysis"
  , "GPCR prediction"
  , "GPCR coupling selectivity prediction"
  , "Transmembrane protein visualisation"
  , "Protein structure assignment"
  , "Protein structure prediction"
  , "Ab initio structure prediction"
  , "Protein modelling"
  , "Protein modelling (mutation)"
  , "Protein modelling (backbone)"
  , "Protein modelling (side chains)"
  , "Protein modelling (loops)"
  , "Protein quaternary structure prediction"
  , "Protein structure analysis"
  , "Protein property calculation (from structure)"
  , "Protein flexibility and motion analysis"
  , "Residue interaction calculation"
  , "Hydrogen bond calculation"
  , "Metal-bound cysteine detection"
  , "Protein-metal contact calculation"
  , "Salt bridge calculation"
  , "Residue distance calculation"
  , "Protein distance matrix calculation"
  , "Protein contact map calculation"
  , "Residue cluster calculation"
  , "Protein geometry calculation"
  , "Ramachandran plot calculation"
  , "Residue interaction prediction"
  , "3D-1D scoring matrix generation"
  , "Protein structural motif recognition"
  , "Protein domain recognition"
  , "Protein peeling"
  , "Protein architecture analysis"
  , "Protein architecture comparison"
  , "Protein architecture recognition"
  , "Protein fold recognition"
  , "Sequence-to-3D-profile alignment"
  , "Protein threading"
  , "Protein structure assignment"
  , "Protein model validation"
  , "Residue bump detection"
  , "Residue packing validation"
  , "Protein geometry validation"
  , "Ramachandran plot validation"
  , "Maximum occurence analysis"
  , "Protein modelling"
  , "Protein modelling (mutation)"
  , "Protein modelling (backbone)"
  , "Protein modelling (side chains)"
  , "Protein modelling (loops)"
  , "Protein secondary structure assignment (from coordinate data)"
  , "Protein cysteine and disulfide bond assignment"
  , "Cysteine bridge detection"
  , "Free cysteine detection"
  , "Metal-bound cysteine detection"
  , "Protein function analysis"
  , "Protein function prediction"
  , "Protein-protein interaction prediction"
  , "Protein subcellular localisation prediction"
  , "Protein signal peptide detection"
  , "Protein signal peptide detection (eukaryotes)"
  , "Protein signal peptide detection (bacteria)"
  , "Protein function comparison"
  , "Protein interaction network comparison"
  , "Protein folding analysis"
  , "Protein folding simulation"
  , "Protein folding pathway prediction"
  , "Protein folding site prediction"
  , "Protein secondary structure analysis"
  , "Protein secondary structure comparison"
  , "Protein secondary structure alignment generation"
  , "Protein architecture comparison"
  , "Protein sequence analysis"
  , "Protein secondary structure prediction"
  , "Protein super-secondary structure prediction"
  , "Transmembrane protein prediction"
  , "GPCR prediction"
  , "Protein secondary structure prediction (integrated)"
  , "Protein secondary structure prediction (helices)"
  , "Protein secondary structure prediction (turns)"
  , "Protein secondary structure prediction (coils)"
  , "Protein secondary structure prediction (disulfide bonds)"
  , "Protein fold recognition"
  , "Sequence-to-3D-profile alignment"
  , "Protein threading"
  , "Protein structure prediction"
  , "Ab initio structure prediction"
  , "Protein modelling"
  , "Protein modelling (mutation)"
  , "Protein modelling (backbone)"
  , "Protein modelling (side chains)"
  , "Protein modelling (loops)"
  , "Protein quaternary structure prediction"
  , "Protein sequence comparison"
  , "Protein sequence feature detection"
  , "Epitope mapping"
  , "Protein post-translation modification site prediction"
  , "Protein signal peptide detection"
  , "Protein signal peptide detection (eukaryotes)"
  , "Protein signal peptide detection (bacteria)"
  , "Protein folding site prediction"
  , "Protein cleavage site prediction"
  , "Protein property calculation (from sequence)"
  , "Peptide immunogenicity prediction"
  , "Enzyme kinetics calculation"
  , "Protein sequence cleavage"
  , "Protein dipole moment calculation"
  , "Protein molecular weight calculation"
  , "Protein fragment weight comparison"
  , "Protein extinction coefficient calculation"
  , "Protein pH-dependent property calculation"
  , "Protein titration curve plotting"
  , "Protein isoelectric point calculation"
  , "Protein hydrogen exchange rate calculation"
  , "3D-1D scoring matrix generation"
  , "GPCR coupling selectivity prediction"
  , "Protein structure comparison"
  , "Protein interaction prediction"
  , "Peptide immunogenicity prediction"
  , "Molecular docking"
  , "Protein-ligand docking"
  , "GPCR coupling selectivity prediction"
  , "Protein-protein interaction prediction"
  , "Protein binding site prediction"
  , "Protein-nucleic acid binding prediction"
  , "Zinc finger prediction"
  , "Protein sequence alignment analysis"
  , "Residue interaction prediction"
  , "Sequence generation (protein)"
  , "Protein sequence cleavage"
  , "de Novo sequencing"
  , "Protein interaction analysis"
  , "Protein interaction raw data analysis"
  , "Protein interaction network analysis"
  , "Protein interaction network comparison"
  , "Protein-nucleic acid binding site analysis"
  , "Protein feature detection"
  , "Protein structural motif recognition"
  , "Protein domain recognition"
  , "Protein peeling"
  , "Protein secondary structure prediction"
  , "Protein super-secondary structure prediction"
  , "Transmembrane protein prediction"
  , "GPCR prediction"
  , "Protein secondary structure prediction (integrated)"
  , "Protein secondary structure prediction (helices)"
  , "Protein secondary structure prediction (turns)"
  , "Protein secondary structure prediction (coils)"
  , "Protein secondary structure prediction (disulfide bonds)"
  , "Protein fold recognition"
  , "Sequence-to-3D-profile alignment"
  , "Protein threading"
  , "Protein binding site prediction"
  , "Protein-nucleic acid binding prediction"
  , "Zinc finger prediction"
  , "Protein sequence feature detection"
  , "Epitope mapping"
  , "Protein post-translation modification site prediction"
  , "Protein signal peptide detection"
  , "Protein signal peptide detection (eukaryotes)"
  , "Protein signal peptide detection (bacteria)"
  , "Protein folding site prediction"
  , "Protein cleavage site prediction"
  , "Protein identification"
  , "Spectral analysis"
  , "Peak detection"
  , "Mass spectra calibration"
  , "Chromatographic alignment"
  , "Deisotoping"
  , "Protein quantification"
  , "Label-free quantification"
  , "Spectral counting"
  , "Ion counting"
  , "Labeled quantification"
  , "SILAC"
  , "iTRAQ"
  , "18O labeling"
  , "TMT-tag"
  , "Dimethyl"
  , "Isotope-coded protein label"
  , "Metabolic labeling"
  , "MRM/SRM"
  , "Peptide identification"
  , "Tag-based peptide identification"
  , "de Novo sequencing"
  , "PTM identification"
  , "PTM localisation"
  , "Peptide database search"
  , "Blind peptide database search"
  , "Validation of peptide-spectrum matches"
  , "Target-Decoy"
  , "Protein identification"
  , "Image analysis"
  , "Cell migration analysis"
  , "Neurite measurement"
  , "Single particle analysis"
  , "Single particle alignment and classification"
  , "Over-representation analysis"
  , "Gene-set enrichment analysis"
  , "Chemical class enrichment"
  , "Text annotation"
  , "Sequence classification"
  , "Variant classification"
  , "Taxonomic classification"
  , "Structure classification"
  , "Protein architecture recognition"
  , "Single particle alignment and classification"
  , "Sequence generation"
  , "Random sequence generation"
  , "Sequence generation (nucleic acid)"
  , "Nucleic acid sequence reverse and complement"
  , "Nucleic acid restriction digest"
  , "Base-calling"
  , "Sequence generation (protein)"
  , "Protein sequence cleavage"
  , "de Novo sequencing"
  , "Probabilistic sequence generation"
  , "Genetic mapping"
  , "Haplotype mapping"
  , "Codon usage table generation"
  , "Sequence distance matrix generation"
  , "Sequence clustering"
  , "Functional clustering"
  , "Sequence profile generation"
  , "3D profile generation"
  , "Gene expression profiling"
  , "Phylogenetic tree generation"
  , "Phylogenetic tree generation (data centric)"
  , "Phylogenetic tree generation (from molecular sequences)"
  , "Phylogenetic footprinting / shadowing"
  , "Phylogenetic species tree construction"
  , "Phylogenetic tree generation (from continuous quantitative characters)"
  , "Phylogenetic tree generation (from gene frequencies)"
  , "Phylogenetic tree construction (from polymorphism data)"
  , "Phylogenetic tree generation (method centric)"
  , "Phylogenetic tree generation (parsimony methods)"
  , "Phylogenetic tree generation (minimum distance methods)"
  , "Phylogenetic tree generation (maximum likelihood and Bayesian methods)"
  , "Phylogenetic tree generation (quartet methods)"
  , "Phylogenetic tree generation (AI methods)"
  , "Phylogenetic tree generation (consensus)"
  , "Phylogenetic tree reconstruction"
  , "Protein secondary structure alignment generation"
  , "RNA secondary structure alignment"
  , "Heat map generation"
  , "3D-1D scoring matrix generation"
  , "Alignment"
  , "Sequence alignment"
  , "Structure-based sequence alignment"
  , "Profile-profile alignment"
  , "Sequence-to-profile alignment"
  , "Pairwise sequence alignment"
  , "Multiple sequence alignment"
  , "Local alignment"
  , "Global alignment"
  , "Constrained sequence alignment"
  , "Tree-based sequence alignment"
  , "Genome alignment"
  , "Read mapping"
  , "Split read mapping"
  , "Structure alignment"
  , "3D profile-to-3D profile alignment"
  , "Pairwise structure alignment"
  , "Multiple structure alignment"
  , "Local structure alignment"
  , "Global structure alignment"
  , "Sequence-to-3D-profile alignment"
  , "Protein threading"
  , "Scaffolding"
  , "Scaffold gap completion"
  , "Sequence checksum generation"
  , "Bibliography generation"
  , "RNA structure covariance model generation"
  , "Probabilistic data generation"
  , "Probabilistic sequence generation"
  , "Deposition"
  , "Sequence clustering"
  , "Functional clustering"
  , "Gene expression profile clustering"
  , "Document clustering"
  , "Sequence assembly"
  , "Mapping assembly"
  , "De-novo assembly"
  , "Genome assembly"
  , "EST assembly"
  , "Localised reassembly"
  , "Scaffolding"
  , "Scaffold gap completion"
  , "Exome assembly"
  , "Transcriptome assembly"
  , "Cross-assembly"
  , "Sequence conversion"
  , "DNA translation"
  , "DNA transcription"
  , "DNA back-translation"
  , "Sequence alignment conversion"
  , "Sequence coordinate conversion"
  , "Sequence composition calculation"
  , "Sequence complexity calculation"
  , "Sequence ambiguity calculation"
  , "Repeat sequence organisation analysis"
  , "Nucleic acid density plotting"
  , "k-mer counting"
  , "Protein property calculation"
  , "Protein property calculation (from structure)"
  , "Protein flexibility and motion analysis"
  , "Residue interaction calculation"
  , "Hydrogen bond calculation"
  , "Metal-bound cysteine detection"
  , "Protein-metal contact calculation"
  , "Salt bridge calculation"
  , "Residue distance calculation"
  , "Protein distance matrix calculation"
  , "Protein contact map calculation"
  , "Residue cluster calculation"
  , "Protein geometry calculation"
  , "Ramachandran plot calculation"
  , "Residue interaction prediction"
  , "3D-1D scoring matrix generation"
  , "Protein hydropathy calculation"
  , "Protein hydrophobic region calculation"
  , "Protein aliphatic index calculation"
  , "Protein hydrophobic moment plotting"
  , "Protein globularity prediction"
  , "Protein solubility prediction"
  , "Protein crystallizability prediction"
  , "Protein property calculation (from sequence)"
  , "Peptide immunogenicity prediction"
  , "Enzyme kinetics calculation"
  , "Protein sequence cleavage"
  , "Protein dipole moment calculation"
  , "Protein molecular weight calculation"
  , "Protein fragment weight comparison"
  , "Protein extinction coefficient calculation"
  , "Protein pH-dependent property calculation"
  , "Protein titration curve plotting"
  , "Protein isoelectric point calculation"
  , "Protein hydrogen exchange rate calculation"
  , "3D-1D scoring matrix generation"
  , "GPCR coupling selectivity prediction"
  , "Nucleic acid property calculation"
  , "Nucleic acid restriction digest"
  , "Nucleic acid thermodynamic property calculation"
  , "Nucleic acid melting profile plotting"
  , "Nucleic acid stitch profile plotting"
  , "Nucleic acid melting curve plotting"
  , "Nucleic acid probability profile plotting"
  , "Nucleic acid temperature profile plotting"
  , "Nucleic acid curvature calculation"
  , "Statistical calculation"
  , "Standardisation and normalisation"
  , "Imputation"
  , "Statistical inference"
  , "Regression analysis"
  , "Statistical modelling"
  , "Isotopic distributions calculation"
  , "Retention times prediction"
  , "Base position variability plotting"
  , "Protein titration curve plotting"
  , "Protein hydrophobic moment plotting"
  , "Nucleic acid melting profile plotting"
  , "Nucleic acid stitch profile plotting"
  , "Nucleic acid melting curve plotting"
  , "Nucleic acid probability profile plotting"
  , "Nucleic acid temperature profile plotting"
  , "Dotplot plotting"
  , "Microarray data rendering"
  , "Heat map generation"
  , "Microarray cluster textual view generation"
  , "Microarray wave graph plotting"
  , "Microarray dendrograph plotting"
  , "Microarray proximity map plotting"
  , "Microarray tree or dendrogram rendering"
  , "Microarray principal component plotting"
  , "Microarray scatter plot plotting"
  , "Whole microarray graph plotting"
  , "Microarray tree-map rendering"
  , "Microarray Box-Whisker plot plotting"
  , "Nucleic acid density plotting"
  , "Codon usage bias plotting"
  , "Incident curve plotting"
  , "Sequence alignment analysis (site correlation)"
  , "Gene expression correlation analysis"
  ]
